
import { theme } from "@/app/theme"
import { ColorSchemeScript, mantineHtmlProps, MantineProvider } from "@mantine/core"

export const metadata = {
    title: 'Админ',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="ru" {...mantineHtmlProps}>
            <head>
                <ColorSchemeScript />
                <meta
                    name="viewport"
                    content=";inimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
                />
            </head>

            <body><MantineProvider theme={theme}>{children}</MantineProvider></body>
        </html>
    )
}
